template: redteamstrategyguide.html
og:image: "https://tyanderson.red/redteamstrategyguide/red-team-strategy-guide-social-preview.jpg"
og:title: "Red Team Strategy Guide"
og:description: "How to thoughtfully approach red teaming within large organizations to maximize business impact."
